config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources 'users'
  resources 'groups', only: [:index, :new, :create]
  resources 'group_users', only: [:new, :create, :index, :show]

  namespace :admin do
    resources :users do
      collection do
        get '/:id/user_tasks', to: 'users#user_tasks'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/calendar' => 'tasks#calendar'
  get 'tasks/chart' => 'tasks#chart'
  resources :tasks do
    put :sort
  end
  get 'tasks/download/:id' => 'tasks#download'
  root 'tasks#index'
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/controllers/group_users_controller.rb
class GroupUsersController < ApplicationController

  def index
    @group = Group.find(params[:group_id])
    @users = @group.users
  end

  def new
  end

  def create
    group_user =  GroupUser.new(group_user_params)
    if group_user.save
      redirect_to user_path(current_user)
      flash[:notice] = 'グループに参加しました！'
    else
      redirect_to user_path(current_user)
      flash[:notice] = '参加に失敗しました'
    end
  end

  def show
    @user = User.find(params[:id])
    @tasks = @user.tasks
  end



  private
  def group_user_params
    @group =  params.permit(:group_id).merge(user_id: current_user.id)
  end
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/views/group_users/index.html.slim
div.margin_top_big.fontsize_midium
  = @group.group_name
  | グループメンバー一覧

div.margin_top_big
  - @users.each do |user|
    div.margin_top
      span.span_margin
        - if user.image.attached?
          = image_tag rails_blob_path(user.image), class: 'image_size_small'
        - else
          span.span_margin_midium
      = link_to user.name, group_user_path(id: user.id, group_id: @group.id)
      span.span_margin
      | さんのタスクを見る

app/views/group_users/show.html.slim
div.margin_top_big
  span.span_margin
    - if @user.image.attached?
      = image_tag rails_blob_path(@user.image), class: 'image_size_small'
  = @user.name
  | さんのタスク一覧

div.margin_top_big
  - if @tasks != nil
    div.inner_yield
      ul.task_list
        - @tasks.each do |task|
          div
            li.task_item
              = task.title
              span.span_margin
                | :
              = task.description
              span.span_margin
                | :
              = task.deadline
              span.span_margin
                | :
              = task.status
              span.span_margin
                | :
              = task.priority
              span.span_margin
              = link_to '編集', edit_task_path(task)
              span.span_margin
              = link_to '削除', task_path(task), method: :delete, data: {confirm: "本当に削除しますか？"}