config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources 'users'
  resources 'groups', only: [:index, :new, :create]
  resources 'group_users', only: [:new, :create, :index, :show]

  namespace :admin do
    resources :users do
      collection do
        get '/:id/user_tasks', to: 'users#user_tasks'
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks/calendar' => 'tasks#calendar'
  get 'tasks/chart' => 'tasks#chart'
  resources :tasks do
    put :sort
  end
  get 'tasks/download/:id' => 'tasks#download'
  root 'tasks#index'
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  has_many :tasks, dependent: :destroy
  has_many :group_users
  has_many :groups, through: :group_users, dependent: :destroy
  has_one_attached :image
  has_secure_password
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length: {minimum: 6}
  before_destroy :check_admin_exist
  before_update :check_admin_exist

  def check_admin_exist
     raise "管理者はこれ以上減らせません" if User.where(admin: true).size <= 1
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin_user
  before_action :set_user, only: [:edit, :update, :destroy, :show, :user_tasks]

  def index
    @users = User.all.order("created_at DESC").includes(:tasks)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_path)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to(admin_users_path)
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to(admin_users_path)
      flash[:notice] = 'ユーザーを削除しました'
    else
      render :index
      flash[:notice] = 'ユーザー削除に失敗しました'
    end
  end

  def show
  end

  def user_tasks
    @tasks = @user.tasks.page(params[:page]).per(10)
  end

  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def require_admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if image = params[:user][:image]
      @user.image.attach(image)
    end
    if @user.save
      log_in @user
      redirect_to @user
      flash[:notice] = "新規登録しました！"
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if image = params[:user][:image]
      @user.image.attach(image)
    end
    if @user.update(user_params)
      redirect_to @user
      flash[:notice] = "プロフィールを更新しました！"
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    gon.overtasks = current_user.tasks.includes(:user).where("deadline < ?", Date.current).map(&:title)
    gon.neartasks = current_user.tasks.includes(:user).where(deadline: Date.current..Date.current+3)
    userparam = params[:username]
    if userparam.present?
      username = User.find_by(name: params[:username])
      @username = params[:username]
      if username != nil
        @tasks = Task.where(user_id: username.id)
      else
        redirect_to @user
        flash[:notice] = "そのようなユーザーは存在しません"
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.slim
div.margin_top_big.fontsize_midium
  | プロフィール変更
  div.margin_top_big

- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    = msg

= form_with model: @user, url: "/users/#{current_user.id}", local: true do |f|
  div
    = f.label :name
    = f.text_field :name
  div
    = f.label :email
    = f.text_field :email
  div
    = f.label :password
    = f.password_field :password
  div
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  div
    = f.label 'プロフィール画像を設定'
    = f.file_field :image
  div.margin_top
    = f.submit value: "プロフィール更新", class: 'btn light-blue accent-2'

app/views/users/new.html.slim
div.margin_top_big.fontsize_midium
  | 新規登録
  div.margin_top_big

- if @user.errors.any?
  - @user.errors.full_messages.each do |msg|
    = msg

= form_with model: @user, url: users_path, local: true do |f|
  div
    = f.label :name
    = f.text_field :name
  div
    = f.label :email
    = f.text_field :email
  div
    = f.label :password
    = f.password_field :password
  div
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  div
    = f.submit value: "新規登録", class: 'btn light-blue accent-2'

app/views/users/show.html.slim
div.margin_top.fontsize_small
  = @user.name
  span.span_margin
  | さんのページ
-if @user.image.attached?
  div.margin_top
    = image_tag rails_blob_path(@user.image), class: 'image_size'




- if @user.admin?
  div.margin_top_big
    span.btn.light-blue.accent-2
      = link_to "管理者ページ", admin_users_path

div.margin_top_big_big
  | グループ検索
  = form_with model: @group, url: groups_path, method: :get, local: true  do |f|
    = f.label "グループ名を入力してください"
    = f.text_field :group_name
    = f.hidden_field :id, value: current_user.id
    = f.submit class: 'btn light-blue accent-2', value: 'グループ検索'

    span.span_margin
    = link_to 'グループ新規作成', new_group_path

- if @group != nil
  div.margin_top_big.fontsize_midium
    = @group.group_name
    span.span_margin
    = form_with model: @group_user, url: "group_users", local: true do |f|
      = f.hidden_field :group_id, value: @group.id
      = f.submit class: 'btn light-blue accent-2', value: 'このグループに参加する'





div.margin_top_big_big.fontsize_small
  | 参加中のグループ一覧
  div.margin_top
    - current_user.groups.each do |group|
      div.margin_top
        = link_to group.group_name, group_users_path(group_id: group.id)




- if @tasks != nil
  div.inner_yield
    ul.task_list
      - @tasks.each do |task|
        div
          li.task_item
            = task.title
            span.span_margin
              | :
            = task.description
            span.span_margin
              | :
            = task.deadline
            span.span_margin
              | :
            = task.status
            span.span_margin
              | :
            = task.priority
            - if task.file.attached?
              span.span_margin
              = link_to '添付ファイルをダウンロード', "tasks/download/#{task.id}", :style => "color:blue;"
            span.span_margin
            = link_to '編集', edit_task_path(task)
            span.span_margin
            = link_to '削除', task_path(task), method: :delete, data: { confirm: "本当に削除しますか？" }